services:
  postgres:
    image: postgres:18
    container_name: taskly-postgres

    environment:
      POSTGRES_DB: taskly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5111:5432"

    volumes:
      - taskly-postgres-data:/var/lib/postgresql

volumes:
  taskly-postgres-data: