services:
  postgres:
    image: postgres:latest
    container_name: taskly-postgres

    environment:
      POSTGRES_DB: taskly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"